# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: Emulator
    pool:
      vmImage: windows-2019
    steps:
      - powershell: |
          gci env:* | sort-object name
          Write-Host "Downloading Cosmos Emulator"
          wget "https://aka.ms/cosmosdb-emulator" -outfile "$env:temp\azure-cosmosdb-emulator.msi"
          Write-Host "Finished Downloading Cosmos Emulator - $env:temp\azure-cosmosdb-emulator.msi"
          dir "$env:temp"
          echo "Deleting Azure Cosmos DB Emulator directory"
          dir "%ProgramFiles%\"
          rmdir /Q /S "%ProgramFiles%\Azure Cosmos DB Emulator"
          echo "Directory after deleting"
          dir "%ProgramFiles%\"
          choco install lessmsi
          choco upgrade lessmsi
          echo "Checking directory" 
          dir "%ProgramFiles%"
          mkdir "%TEMP%\Azure Cosmos DB Emulator"
          lessmsi x "%TEMP%\azure-cosmosdb-emulator.msi" "%TEMP%\Azure Cosmos DB Emulator\"
          dir "%TEMP%"
          dir "%Temp%\Azure Cosmos DB Emulator\"
          dir "$env:Temp\"
          dir "$env:Temp\Azure Cosmos DB Emulator"
          dir "$env:Temp\Azure Cosmos DB Emulator\SourceDir\"
          dir "$env:Temp\Azure Cosmos DB Emulator\SourceDir\Azure Cosmos DB Emulator"
          Write-Host "Starting Comsos DB Emulator"
          Start-Process "$env:Temp\Azure Cosmos DB Emulator\SourceDir\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe" "/NoExplorer /NoUI" -Verb RunAs
        displayName: "Refresh and Run Public Cosmos DB Emulator"
      - task: NodeTool@0
        inputs:
          versionSpec: "8.x"
        displayName: "Install Node.js"

      - script: npm install
        displayName: "npm install"

      - script: npm run build
        displayName: "npm run build"

      - bash: ACCOUNT_HOST=$COSMOSDBEMULATOR_ENDPOINT NODE_TLS_REJECT_UNAUTHORIZED="0" npm run test
        failOnStderr: true
        displayName: "npm test"
        env:
          MOCHA_TIMEOUT: 100000
  # - job: NightlyEmulator
  #   pool:
  #     vmImage: vs2017-win2016
  #   steps:
  #     - task: azure-cosmosdb.emulator-internal-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
  #       displayName: "Run Azure Cosmos DB Emulator container"
  #       inputs:
  #         username: "$(cosmosdb.azurecr.io.Username)"
  #         password: "$(cosmosdb.azurecr.io.Password)"
  #         defaultPartitionCount: 25
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: "8.x"
  #       displayName: "Install Node.js"

  #     - script: npm install
  #       displayName: "npm install"

  #     - script: npm run build
  #       displayName: "npm run build"

  #     - bash: ACCOUNT_HOST=$COSMOSDBEMULATOR_ENDPOINT NODE_TLS_REJECT_UNAUTHORIZED="0" npm run test
  #       failOnStderr: true
  #       continueOnError: true
  #       displayName: "npm test"
  #       env:
  #         MOCHA_TIMEOUT: 100000
