# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: Staging
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - script: |
        npm run test
      displayName: 'npm run test'
      env:
        ACCOUNT_HOST: $(stagingEndpoint)
        ACCOUNT_KEY: $(stagingKey)
        MOCHA_TIMEOUT: 100000
        TESTS_MULTIREGION: true
  - job: Emulator
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: azure-cosmosdb.emulator-public-preview.run-cosmosdbemulatorcontainer.CosmosDbEmulator@2
      displayName: 'Run Azure Cosmos DB Emulator container'
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - script: |
        npm run test
      displayName: 'npm run test'
      env:
        MOCHA_TIMEOUT: 100000
        TESTS_MULTIREGION: true
